server:
  port: 8081

      

spring:
  application:
    name: authentication
  data:
    mongodb:
      uri: mongodb+srv://shubhangandas7366:Swarnoflick5@eventpulsenosql.tzevydl.mongodb.net/EventPulseDB
      database: EventPulseDB

# Custom JWT Configuration (these are our custom properties)

jwt:
  secret: ShubhanganDasSecretKey@12345

app:
  jwt:
    secret: mySecretKey12345678901234567890123456789012345678901234567890
    expiration: 86400000 # 24 hours in milliseconds

