
spring:
    application:
     name: events
    datasource:
        url: jdbc:postgresql://localhost:5432/eventpulseSQL
        username: postgres
        password: Swarnoflick5@
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate: 
            ddl-auto: update 
            # it checks whether table is there or not it creates if not present and updates if present. using 'create'  in this place will create a new table everytime.
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

